name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.PRODUCTION_SSH_KEY }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add remote host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan discovery.nandaba.de >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Transfer Repository Files to Production Server
      run: |
        rsync -avz --exclude '.git' --exclude 'node_modules' ./ root@discovery.nandaba.de:/opt/dockervolumes/de.reinhardeichhorn/btfv.tablesoccer.rocks/

    - name: Build Docker images on Production Server
      run: |
        ssh root@discovery.nandaba.de "
          cd /opt/dockervolumes/de.reinhardeichhorn/btfv.tablesoccer.rocks && \
          docker build -t scraper-image -f src/scraper/Dockerfile . && \
          docker build -t web-image -f src/web_app/Dockerfile ."

    - name: Deploy to Production Server
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      run: |
        ssh root@discovery.nandaba.de "
          cd /opt/dockervolumes/de.reinhardeichhorn/btfv.tablesoccer.rocks && \
          docker-compose --env-file .env.prod -f docker-compose-prod.yml up -d"
